// Mocks generated by Mockito 5.4.4 from annotations
// in home_activity_suggestions/test/features/authentication/presentation/auth_screen_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_activity_suggestions/core/data/result.dart' as _i4;
import 'package:home_activity_suggestions/features/authentication/domain/entities/auth_screen_data.dart'
    as _i10;
import 'package:home_activity_suggestions/features/authentication/domain/entities/domain_user.dart'
    as _i5;
import 'package:home_activity_suggestions/features/authentication/domain/usecases/create_account.dart'
    as _i2;
import 'package:home_activity_suggestions/features/authentication/domain/usecases/logout.dart'
    as _i7;
import 'package:home_activity_suggestions/features/authentication/domain/usecases/sign_in.dart'
    as _i8;
import 'package:home_activity_suggestions/features/authentication/domain/usecases/switch_auth_screen_mode.dart'
    as _i9;
import 'package:home_activity_suggestions/features/authentication/presentation/providers/auth_screen_error_message_builder.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeException_0 extends _i1.SmartFake implements Exception {
  _FakeException_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CreateAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateAccount extends _i1.Mock implements _i2.CreateAccount {
  MockCreateAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.DomainUser>> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.DomainUser>>.value(
            _i6.dummyValue<_i4.Result<_i5.DomainUser>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.DomainUser>>);
}

/// A class which mocks [Logout].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogout extends _i1.Mock implements _i7.Logout {
  MockLogout() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignIn extends _i1.Mock implements _i8.SignIn {
  MockSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.DomainUser>> call({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.DomainUser>>.value(
            _i6.dummyValue<_i4.Result<_i5.DomainUser>>(
          this,
          Invocation.method(
            #call,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.DomainUser>>);
}

/// A class which mocks [SwitchAuthScreenMode].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwitchAuthScreenMode extends _i1.Mock
    implements _i9.SwitchAuthScreenMode {
  MockSwitchAuthScreenMode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call() => super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DomainUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockDomainUser extends _i1.Mock implements _i5.DomainUser {
  MockDomainUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [Success].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuccess<T> extends _i1.Mock implements _i4.Success<T> {
  MockSuccess() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T get value => (super.noSuchMethod(
        Invocation.getter(#value),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.getter(#value),
        ),
      ) as T);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [Failure].
///
/// See the documentation for Mockito's code generation for more information.
class MockFailure<T> extends _i1.Mock implements _i4.Failure<T> {
  MockFailure() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Exception get exception => (super.noSuchMethod(
        Invocation.getter(#exception),
        returnValue: _FakeException_0(
          this,
          Invocation.getter(#exception),
        ),
      ) as Exception);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [AuthOrganismDynamicData].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthOrganismDynamicData extends _i1.Mock
    implements _i10.AuthOrganismDynamicData {
  MockAuthOrganismDynamicData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get topMessage => (super.noSuchMethod(
        Invocation.getter(#topMessage),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#topMessage),
        ),
      ) as String);

  @override
  String get submitButtonText => (super.noSuchMethod(
        Invocation.getter(#submitButtonText),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#submitButtonText),
        ),
      ) as String);

  @override
  String get changeScreenModeButtonText => (super.noSuchMethod(
        Invocation.getter(#changeScreenModeButtonText),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#changeScreenModeButtonText),
        ),
      ) as String);

  @override
  _i10.AuthMode get authMode => (super.noSuchMethod(
        Invocation.getter(#authMode),
        returnValue: _i10.AuthMode.signIn,
      ) as _i10.AuthMode);
}

/// A class which mocks [AuthScreenErrorMessageBuilder].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthScreenErrorMessageBuilder extends _i1.Mock
    implements _i11.AuthScreenErrorMessageBuilder {
  MockAuthScreenErrorMessageBuilder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? getMessage({required String? errorCode}) =>
      (super.noSuchMethod(Invocation.method(
        #getMessage,
        [],
        {#errorCode: errorCode},
      )) as String?);
}
