// Mocks generated by Mockito 5.4.4 from annotations
// in home_activity_suggestions/test/features/authentication/domain/usecases/switch_auth_screen_mode_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:home_activity_suggestions/features/authentication/domain/entities/auth_screen_data.dart'
    as _i5;
import 'package:home_activity_suggestions/features/authentication/presentation/providers/auth_screen_mode_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthScreenModeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthScreenModeNotifier extends _i1.Mock
    implements _i2.AuthScreenModeNotifier {
  MockAuthScreenModeNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i3.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i4.Stream<_i5.AuthMode> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i5.AuthMode>.empty(),
      ) as _i4.Stream<_i5.AuthMode>);

  @override
  _i5.AuthMode get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i5.AuthMode.signIn,
      ) as _i5.AuthMode);

  @override
  set state(_i5.AuthMode? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.AuthMode get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _i5.AuthMode.signIn,
      ) as _i5.AuthMode);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void switchMode() => super.noSuchMethod(
        Invocation.method(
          #switchMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i5.AuthMode? old,
    _i5.AuthMode? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.RemoveListener addListener(
    _i6.Listener<_i5.AuthMode>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i3.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
